# Generated by Django 5.1.4 on 2025-01-23 16:49

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(help_text='Nome do usuário', max_length=30, verbose_name='Nome')),
                ('last_name', models.CharField(help_text='Sobrenome do usuário', max_length=70, verbose_name='Sobrenome')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do produto', max_length=20, verbose_name='Nome')),
                ('price', models.DecimalField(decimal_places=0, help_text='Preço do produto', max_digits=10, verbose_name='Preço')),
                ('stock', models.IntegerField(help_text='Quantidade em estoque', verbose_name='Estoque')),
                ('reserved_stock', models.IntegerField(default=0, help_text='Quantidade empenhada em pedidos', verbose_name='Estoque reservado')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do produto', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização do produto', verbose_name='Atualizado em')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('endpoint', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('headers', models.TextField()),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pendente'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado')], default='PEN', help_text='Status do pedido', max_length=3, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação do pedido', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de atualização do pedido', verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='Usuário que fez o pedido', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('product', models.ForeignKey(help_text='Produto do pedido', on_delete=django.db.models.deletion.PROTECT, to='app.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, help_text='Saldo disponível', max_digits=10, verbose_name='Saldo')),
                ('reserved_balance', models.DecimalField(decimal_places=0, default=0, help_text='Saldo empenhado em pedidos', max_digits=10, verbose_name='Saldo empenhado')),
                ('user', models.OneToOneField(help_text='Usuário dono da carteira', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Carteira',
                'verbose_name_plural': 'Carteiras',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=0, help_text='Valor da transação', max_digits=10, null=True, verbose_name='Valor')),
                ('type', models.CharField(choices=[('ADD', 'Adição de fundos'), ('DEB', 'Débito de fundos')], default='ADD', help_text='Tipo da transação', max_length=3, verbose_name='Tipo')),
                ('detail', models.CharField(help_text='Detalhes da transação', max_length=100, verbose_name='Detalhes')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da transação', verbose_name='Criado em')),
                ('order', models.ForeignKey(blank=True, help_text='Pedido relacionado à transação', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.order', verbose_name='Pedido')),
                ('wallet', models.ForeignKey(help_text='Carteira relacionada à transação', on_delete=django.db.models.deletion.PROTECT, to='app.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Transação',
                'verbose_name_plural': 'Transações',
            },
        ),
    ]
