# Generated by Django 5.1.4 on 2025-01-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('COM', 'Committed'), ('CAN', 'Canceled'), ('CON', 'Concluded')], default='COM', max_length=3),
        ),
    ]
