# Generated by Django 5.1.4 on 2025-01-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image representing the item.', null=True, upload_to='uploads/items/', verbose_name='Item Image'),
        ),
    ]
