# Generated by Django 5.1.4 on 2025-01-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.order', verbose_name='Associated Order'),
        ),
    ]
