# Generated by Django 5.1.4 on 2025-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_trade_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image representing the item.', null=True, upload_to='public/', verbose_name='Item Image'),
        ),
    ]
